language: python
cache:
  - pip
python:
  - 3.5
install:
  - pip install -U setuptools
  - pip install -r requirements.txt
script:
  - flake8 . --max-line-length=100 --exclude=migrations/versions,bin
  - isort